name: GitHub Actions Demo
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}