name: GitHub Actions Demo
on:
  push: 
    branches:
      - main
  issues:
    types: [opened, edited, milestoned]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}